---
- name: Deploy Nginx Docker Container
  hosts: nginx
  become: true
  collections:
    - community.docker

  tasks:
    - name: Create directory for nginx config
      file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /opt/nginx/conf
        - /opt/nginx/html

    - name: Copy nginx configuration
      copy:
        content: |
          server {
              listen 80;
              root /usr/share/nginx/html;

              location / {
                  index index.html index.htm;
                  try_files $uri $uri/ /index.html =404;
              }

              error_page 404 /index.html;
              location = /404 {
                  return 404;
              }
          }
        dest: /opt/nginx/conf/default.conf
        mode: "0644"

    - name: Copy index.html
      copy:
        src: index.html
        dest: /opt/nginx/html/index.html
        mode: "0644"

    - name: Pull Nginx Docker image
      community.docker.docker_image:
        name: nginx:latest
        source: pull

    - name: Run Nginx container
      community.docker.docker_container:
        name: nginx-container
        image: nginx:latest
        state: started
        ports:
          - "8081:80"
        volumes:
          - /opt/nginx/conf/default.conf:/etc/nginx/conf.d/default.conf:ro
          - /opt/nginx/html:/usr/share/nginx/html:ro
        restart_policy: always
